# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/grpc-compatibility/proto/compatibility.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'services/grpc-compatibility/proto/compatibility.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5services/grpc-compatibility/proto/compatibility.proto\x12\rcompatibility\";\n\x14\x43ompatibilityRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\npartner_id\x18\x02 \x01(\x05\"L\n\x15\x43ompatibilityResponse\x12\x1d\n\x15overall_compatibility\x18\x01 \x01(\x01\x12\x14\n\x0c\x64\x65tails_json\x18\x02 \x01(\t2{\n\x14\x43ompatibilityService\x12\x63\n\x16\x43\x61lculateCompatibility\x12#.compatibility.CompatibilityRequest\x1a$.compatibility.CompatibilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.grpc_compatibility.proto.compatibility_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPATIBILITYREQUEST']._serialized_start=72
  _globals['_COMPATIBILITYREQUEST']._serialized_end=131
  _globals['_COMPATIBILITYRESPONSE']._serialized_start=133
  _globals['_COMPATIBILITYRESPONSE']._serialized_end=209
  _globals['_COMPATIBILITYSERVICE']._serialized_start=211
  _globals['_COMPATIBILITYSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
