# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.grpc_compatibility.proto import compatibility_pb2 as services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services/grpc_compatibility/proto/compatibility_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompatibilityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateCompatibility = channel.unary_unary(
                '/compatibility.CompatibilityService/CalculateCompatibility',
                request_serializer=services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2.CompatibilityRequest.SerializeToString,
                response_deserializer=services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2.CompatibilityResponse.FromString,
                _registered_method=True)


class CompatibilityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CalculateCompatibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompatibilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateCompatibility': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateCompatibility,
                    request_deserializer=services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2.CompatibilityRequest.FromString,
                    response_serializer=services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2.CompatibilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compatibility.CompatibilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('compatibility.CompatibilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompatibilityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateCompatibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compatibility.CompatibilityService/CalculateCompatibility',
            services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2.CompatibilityRequest.SerializeToString,
            services_dot_grpc__compatibility_dot_proto_dot_compatibility__pb2.CompatibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
