# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/grpc-twin/proto/twin.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'services/grpc-twin/proto/twin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#services/grpc-twin/proto/twin.proto\x12\x04twin\"X\n\x13TwinSimulateRequest\x12\x11\n\tuser_a_id\x18\x01 \x01(\x05\x12\x11\n\tuser_b_id\x18\x02 \x01(\x05\x12\x1b\n\x13\x63ompatibility_score\x18\x03 \x01(\x01\"a\n\x14TwinSimulateResponse\x12\x13\n\x0b\x65nvironment\x18\x01 \x01(\t\x12\x19\n\x11\x64ialogue_log_json\x18\x02 \x01(\t\x12\x19\n\x11match_detail_json\x18\x03 \x01(\t2T\n\x0bTwinService\x12\x45\n\x0cSimulateDate\x12\x19.twin.TwinSimulateRequest\x1a\x1a.twin.TwinSimulateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.grpc_twin.proto.twin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TWINSIMULATEREQUEST']._serialized_start=45
  _globals['_TWINSIMULATEREQUEST']._serialized_end=133
  _globals['_TWINSIMULATERESPONSE']._serialized_start=135
  _globals['_TWINSIMULATERESPONSE']._serialized_end=232
  _globals['_TWINSERVICE']._serialized_start=234
  _globals['_TWINSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
