# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.grpc_twin.proto import twin_pb2 as services_dot_grpc__twin_dot_proto_dot_twin__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services/grpc_twin/proto/twin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwinServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateDate = channel.unary_unary(
                '/twin.TwinService/SimulateDate',
                request_serializer=services_dot_grpc__twin_dot_proto_dot_twin__pb2.TwinSimulateRequest.SerializeToString,
                response_deserializer=services_dot_grpc__twin_dot_proto_dot_twin__pb2.TwinSimulateResponse.FromString,
                _registered_method=True)


class TwinServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SimulateDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateDate': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateDate,
                    request_deserializer=services_dot_grpc__twin_dot_proto_dot_twin__pb2.TwinSimulateRequest.FromString,
                    response_serializer=services_dot_grpc__twin_dot_proto_dot_twin__pb2.TwinSimulateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twin.TwinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twin.TwinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwinService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimulateDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twin.TwinService/SimulateDate',
            services_dot_grpc__twin_dot_proto_dot_twin__pb2.TwinSimulateRequest.SerializeToString,
            services_dot_grpc__twin_dot_proto_dot_twin__pb2.TwinSimulateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
